In [4]:
import pandas as pd 

df = pd.read_csv("appartment.csv" , sep='\t')

df

    Appartment  Area  Rooms    Price
0            1   130      3  145,000
1            2   200      3  215,000
2            3   250      4  270,000
3            4   100      3  115,000
4            5   110      2  120,000
5            6    90      1   95,000
6            7   180      4  200,000
7            8   160      3  175,000
8            9   230      5  255,000
9           10   210      4  230,000
10          11   245      5  270,000
11          12   225      4  245,000
12          13   190      4  210,000
13          14   166      3  181,000
14          15   134      3  149,000
15          16   111      3  126,000
16          17    95      2  105,000
17          18   118      2  128,000
18          19   189      3  204,000
19          20   278      5  303,000
20          21   300      5  325,000
21          22   290      5  315,000
22          23   270      4  290,000
23          24   260      4  280,000
24          25   287      5  312,000
25          26   267      4  287,000
26          27   199      3  214,000
27          28   189      3  204,000
28          29   206      4  226,000
29          30   298      5  323,000

In [5]:
df['Price'] = df['Price'].str.replace(',', '').astype(float)
X = df[['Area', 'Rooms']]

Y = df['Price']

X

    Area  Rooms
0    130      3
1    200      3
2    250      4
3    100      3
4    110      2
5     90      1
6    180      4
7    160      3
8    230      5
9    210      4
10   245      5
11   225      4
12   190      4
13   166      3
14   134      3
15   111      3
16    95      2
17   118      2
18   189      3
19   278      5
20   300      5
21   290      5
22   270      4
23   260      4
24   287      5
25   267      4
26   199      3
27   189      3
28   206      4
29   298      5

In [6]:
from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor()
model.fit(X, Y)


print("Im ready for training")

Im ready for training

In [7]:
def new_appertment (Area , Rooms) :

    data = [[Area, Rooms]]

    predection = model.predict(data)

    print( "The price of the appartment = ",predection[0])

In [8]:
user_area = float(input("Enter the area : "))
user_rooms = int(input("Enter the numbers of rooms : "))
print("-"*30)
print("Deep thinking....")
print("-"*30)
new_appertment(user_area , user_rooms)

------------------------------
Deep thinking....
------------------------------
The price of the appartment =  210000.0

c:\Users\Mo3az Diyaa\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(